repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=88]
        language_version: python3.12
  - repo: https://github.com/Carreau/velin
    rev: '0.0.12'
    hooks:
      - id: velin
