name: Run tests and coverage

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_call:
  workflow_dispatch:

env:
  PAT_DATA_FOLDER: ${{ github.workspace }}/data

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest, macos-14]

    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
    - name: Install dependencies
      run: uv sync --locked --group test
    - name: Linting
      run: |
        uv run ruff check --output-format=github --select=E9,F63,F7,F82 --target-version=py310 . # Should do wider tests in the future.
    - name: Run tests
      run: |
        cd tests
        uv run python -m unittest
