name: Release

on:
  - release
  - push

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Run tests, build wheels and upload.
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
      - name: Run Tests
        call-workflow:
          uses: ./.github/workflows/run_tests.yml
      - name: Build wheels
        call-workflow:
          uses: ./.github/workflows/build_wheels.yml
