name: Release

on:
  release:
    types:
      - created
  push:
    branches:
      - newworkflow
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: "Run tests"
    uses: BohndiekLab/patato/.github/workflows/run_tests.yml@newworkflow
  build_wheels:
    name: "Build wheels"
    uses: BohndiekLab/patato/.github/workflows/build_wheels.yml@newworkflow
  publish:
    runs-on: ubuntu-latest
    name: Upload to PyPi.
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Display structure of downloaded files
        run: ls -R
