name: Release

on:
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  test_run:
    name: "Check versions"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Display structure of downloaded files
        run: ls -R
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools_scm
      - name: Display version number
        run: python -m setuptools_scm
      - name: Show github tags
        run: git tag | cat
  build_wheels:
    name: "Build wheels"
    uses: BohndiekLab/patato/.github/workflows/build_wheels.yml@main # Can't get this to work with local version.
  publish-dummy:
    needs: build_wheels
    runs-on: ubuntu-latest
    name: Dummy upload to PyPI
    environment:
      name: testpypi
      url: https://test.pypi.org/p/patato
    permissions:
      id-token: write
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Move artifacts to dist folder.
        run: mv dist/artifact/* dist
      - name: Delete artifact folder.
        run: rm -r dist/artifact
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Display structure of downloaded files
        run: ls -R
  publish:
    needs: build_wheels
    runs-on: ubuntu-latest
    name: Upload to PyPI.
    if: github.event_name == 'release'
    environment:
      name: pypi
      url: https://pypi.org/p/patato
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Move artifacts to dist folder.
        run: mv dist/artifact/* dist
      - name: Delete artifact folder.
        run: rm -r dist/artifact
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
