name: Release

on:
  - release
  - push

jobs:
  test:
    name: "Run tests"
    uses: ./github/workflows/run_tests.yml
  build_wheels:
    name: "Build wheels"
    uses: ./github/workflows/build_wheels.yml
  publish:
    runs-on: ubuntu-latest
    name: Upload to PyPi.
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Display structure of downloaded files
        run: ls -R
